# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: nutriplan-api-tests
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dan
      POSTGRES_PASSWORD: nutriplan
      POSTGRES_DB: tests
