name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build app
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: postgresql://dan:nutriplan@localhost:5433/tests
